SELECT *
  FROM GE_PESSOA@LINK_C5 Z
 WHERE EXISTS (SELECT 1
          FROM NAGV_PLUSOFT_PESSOA_BASE X
         WHERE X.ODR > 1
               AND LPAD(IDPESSOA,14,0) = LPAD(NROCGCCPF, 12, 0) || LPAD(DIGCGCCPF, 2, 0)
         )
         ORDER BY NOMERAZAO ASC
