ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

CREATE OR REPLACE VIEW CONSINCO.NAGV_PLUSOFT_PRODUTO AS

SELECT X.SEQPRODUTO IDPRODUTO,
       X.DESCCOMPLETA TXTDESCRICAOCOMPLETA,
       X.DESCREDUZIDA TXTDESCRICAORESUMIDA,
       1 UNIDADE,
       NULL TXTDEPTO,
       NULL TXTSECAO,
       C.CATEGORIACOMPLETA TXTCATEGORIA,
       NULL TXTGRUPO,
       NULL TXTSUBGRUPO,
       MARCA TXTMARCA,
       NULL TXTFABRICANTE,
       CASE WHEN MARCA = 'NAGUMO' THEN 1 ELSE 0 END FLGMARCAPROPRIA,
       CASE WHEN CATEGORIAN1 = 'SAZONALIDADE' THEN 1 ELSE 0 END FLGPORDUTOSAZONAL,
       CASE WHEN FD.FINALIDADEFAMILIA = 'S' THEN 1 ELSE 0 END FLGSERVICO,
       B.SEQPRODUTO IDMATERIALPAI,
       B.DESCCOMPLETA TXTDESCRICAOMATERIALPAI,
       SEQFORNECEDOR IDFORNECEDOR,
       NOMERAZAO TXTNOMEFORNECEDOR
       
  FROM MAP_PRODUTO X INNER JOIN DIM_CATEGORIA@CONSINCODW C ON C.SEQFAMILIA = X.SEQFAMILIA 
                     INNER JOIN MAP_FAMILIA F ON F.SEQFAMILIA = X.SEQFAMILIA
                      LEFT JOIN MAP_MARCA M ON M.SEQMARCA = F.SEQMARCA
                      LEFT JOIN MAP_FAMFORNEC Z ON Z.SEQFAMILIA = X.SEQFAMILIA AND Z.PRINCIPAL = 'S'
                     INNER JOIN GE_PESSOA G ON G.SEQPESSOA = Z.SEQFORNECEDOR
                      LEFT JOIN MAP_PRODUTO B ON B.SEQPRODUTO = X.SEQPRODUTOBASE 
                     INNER JOIN MAP_FAMDIVISAO FD ON FD.SEQFAMILIA = X.SEQFAMILIA
 
