CREATE OR REPLACE VIEW CONSINCO.NAGV_PLUSOFT_VENDAS AS

SELECT XX.IDPESSOA,IDFILIAL, IDCUPOM, IDPRODUTO, XX.DATVENDA, 
       SUM(XX.NUMQTDVENDIDA) NUMQTDVENDIDA, 
       SUM(VLRPRECOVENDAUNITARIO) VLRPRECOVENDAUNITARIO, 
       SUM(VLRPRECOPDVUNITARIO) VLRPRECOPDVUNITARIO,
       SUM(VLRDESCONTOUNITARIO) VLRDESCONTOUNITARIO, 
       VLRMARGEMPDV, TXTCANALVENDAS, TXTTIPOVENDA, IDFORMAPAGTO, TXTFORMAPAGTO

  FROM (

SELECT CASE WHEN FISICAJURIDICA = 'F' THEN LPAD(NROCGCCPF,9,0)||LPAD(DIGCGCCPF,2,0) 
         ELSE LPAD(NROCGCCPF,12,0)||LPAD(DIGCGCCPF,2,0) END IDPESSOA,
       X.NROEMPRESA IDFILIAL,
       X.SEQNF IDCUPOM,
       X.SEQPRODUTO IDPRODUTO,
       TO_DATE(TO_CHAR(DTAOPERACAO, 'DD/MM/RRRR') || ' ' ||
                        HORAOPERACAO || ':' || MINUTOOPERACAO,
                        'DD/MM/RRRR HH24:MI') DATVENDA, 
       QTDOPERACAO * DECODE( X.TIPCGO, 'E', -1, 1 ) NUMQTDVENDIDA,
       ROUND((NVL(NULLIF(VLRPROMOC,0), VLROPERACAO) / NVL(NULLIF(QTDOPERACAO,0), PESOBRUTO)) - NAGF_BUSCAVLRDEV(X.SEQNF, X.SEQPRODUTO),2) VLRPRECOVENDAUNITARIO,
       ROUND((NVL(NULLIF(VLRPROMOC,0), VLROPERACAO) / NVL(NULLIF(QTDOPERACAO,0), PESOBRUTO)) - NAGF_BUSCAVLRDEV(X.SEQNF, X.SEQPRODUTO),2) VLRPRECOPDVUNITARIO,
       ROUND(VLROPERACAO - NVL(NULLIF(VLRPROMOC,0), VLROPERACAO)) VLRDESCONTOUNITARIO,
       ROUND((( X.VLROPERACAO - X.VVLRCTOLIQUIDO - X.VVLRIMPOSTOSAIDA - NVL( X.VLRDESPOPERACIONALITEM, 0 ) - X.VLRCOMISSAO - X.VLRVERBACOMPRA - X.VLRCALCIMPOSTOVDA ) / (X.VLROPERACAO)*100),2) VLRMARGEMPDV,
       DECODE(X.NROSEGMENTO,5,'E-COMMERCE','LOJA') TXTCANALVENDAS,
       'VENDA' TXTTIPOVENDA,
       X.NROFORMAPAGTO IDFORMAPAGTO,
       FORMAPAGTO TXTFORMAPAGTO

  FROM FATO_VENDA@CONSINCODW X  INNER JOIN GE_PESSOA G ON G.SEQPESSOA = X.SEQCLIENTE
                                INNER JOIN MON_FORMAPAGTO F ON F.NROFORMAPAGTO = X.NROFORMAPAGTO
                                
 WHERE 1=1
   AND X.CODGERALOPER IN (37,48,123,610,615,613,810,916,910,911)
   AND NOT EXISTS (SELECT 1 FROM MFL_DOCTOFISCAL DF WHERE DF.STATUSDF = 'C' AND DF.SEQNF = X.SEQNF)

  ) XX
 
GROUP BY XX.IDPESSOA,IDFILIAL, IDCUPOM, IDPRODUTO, XX.DATVENDA, 
         VLRMARGEMPDV, TXTCANALVENDAS, TXTTIPOVENDA,
         IDFORMAPAGTO, TXTFORMAPAGTO

ORDER BY 9 ASC

-- NO DW

CREATE OR REPLACE VIEW CONSINCODW.NAGV_PLUSOFT_VENDAS AS

SELECT XX.IDPESSOA,IDFILIAL, IDCUPOM, IDPRODUTO, XX.DATVENDA, 
       SUM(XX.NUMQTDVENDIDA) NUMQTDVENDIDA, 
       SUM(VLRPRECOVENDAUNITARIO) VLRPRECOVENDAUNITARIO, 
       SUM(VLRPRECOPDVUNITARIO) VLRPRECOPDVUNITARIO,
       SUM(VLRDESCONTOUNITARIO) VLRDESCONTOUNITARIO, 
       VLRMARGEMPDV, TXTCANALVENDAS, TXTTIPOVENDA, IDFORMAPAGTO, TXTFORMAPAGTO

  FROM (

SELECT CASE WHEN FISICAJURIDICA = 'F' THEN LPAD(NROCGCCPF,9,0)||LPAD(DIGCGCCPF,2,0) 
         ELSE LPAD(NROCGCCPF,12,0)||LPAD(DIGCGCCPF,2,0) END IDPESSOA,
       X.NROEMPRESA IDFILIAL,
       X.SEQNF IDCUPOM,
       X.SEQPRODUTO IDPRODUTO,
       TO_DATE(TO_CHAR(DTAOPERACAO, 'DD/MM/RRRR') || ' ' ||
                        HORAOPERACAO || ':' || MINUTOOPERACAO,
                        'DD/MM/RRRR HH24:MI') DATVENDA, 
       QTDOPERACAO * DECODE( X.TIPCGO, 'E', -1, 1 ) NUMQTDVENDIDA,
       ROUND((NVL(NULLIF(VLRPROMOC,0), VLROPERACAO) / NVL(NULLIF(QTDOPERACAO,0), PESOBRUTO)) - NAGF_BUSCAVLRDEV(X.SEQNF, X.SEQPRODUTO),2) VLRPRECOVENDAUNITARIO,
       ROUND((NVL(NULLIF(VLRPROMOC,0), VLROPERACAO) / NVL(NULLIF(QTDOPERACAO,0), PESOBRUTO)) - NAGF_BUSCAVLRDEV(X.SEQNF, X.SEQPRODUTO),2) VLRPRECOPDVUNITARIO,
       ROUND(VLROPERACAO - NVL(NULLIF(VLRPROMOC,0), VLROPERACAO)) VLRDESCONTOUNITARIO,
       ROUND((( X.VLROPERACAO - X.VVLRCTOLIQUIDO - X.VVLRIMPOSTOSAIDA - NVL( X.VLRDESPOPERACIONALITEM, 0 ) - X.VLRCOMISSAO - X.VLRVERBACOMPRA - X.VLRCALCIMPOSTOVDA ) / (X.VLROPERACAO)*100),2) VLRMARGEMPDV,
       DECODE(X.NROSEGMENTO,5,'E-COMMERCE','LOJA') TXTCANALVENDAS,
       'VENDA' TXTTIPOVENDA,
       X.NROFORMAPAGTO IDFORMAPAGTO,
       FORMAPAGTO TXTFORMAPAGTO

  FROM FATO_VENDA X  INNER JOIN GE_PESSOA@LINK_C5 G ON G.SEQPESSOA = X.SEQCLIENTE
                     INNER JOIN MON_FORMAPAGTO@LINK_C5 F ON F.NROFORMAPAGTO = X.NROFORMAPAGTO
                                
 WHERE 1=1
   AND X.CODGERALOPER IN (37,48,123,610,615,613,810,916,910,911)
   AND NOT EXISTS (SELECT 1 FROM MFL_DOCTOFISCAL@LINK_C5 DF WHERE DF.STATUSDF = 'C' AND DF.SEQNF = X.SEQNF)

  ) XX
 
GROUP BY XX.IDPESSOA,IDFILIAL, IDCUPOM, IDPRODUTO, XX.DATVENDA, 
         VLRMARGEMPDV, TXTCANALVENDAS, TXTTIPOVENDA,
         IDFORMAPAGTO, TXTFORMAPAGTO

ORDER BY 9 ASC
