CREATE OR REPLACE VIEW CONSINCODW.NAGV_PLUSOFT_PESSOA_V2 AS 

SELECT IDPESSOA, TXTNOMECOMPLETO, TXTESTADOCIVIL, TXTSEXO, DATNASCIMENTO, 
       DATULTCOMPRA, DATATUALIZACAOCADASTRO, DATCADASTRO, NUMCEL1, NUMCEL2, NUMTELFIXO,
       NUMTELCOMERCIAL, TXTEMAIL, TXTENDERECO, TXTBAIRRO, TXTCIDADE, ESTADO
       
  FROM (
  
SELECT ROW_NUMBER() 
          OVER(PARTITION BY IDPESSOA 
               ORDER BY LENGTH(IDPESSOA||TXTNOMECOMPLETO||TXTESTADOCIVIL||TXTSEXO||DATNASCIMENTO||
                               DATULTCOMPRA||DATATUALIZACAOCADASTRO||DATCADASTRO||NUMCEL1||NUMCEL2||
                               NUMTELFIXO||NUMTELCOMERCIAL||TXTEMAIL||TXTENDERECO||TXTBAIRRO||TXTCIDADE||ESTADO) DESC) RN,
                               
                               /*SELECT LISTAGG(COLUMN_NAME,', ') WITHIN GROUP (ORDER BY COLUMN_ID)
                                   FROM ALL_TAB_COLUMNS A
                                  WHERE A.table_name = 'NAGV_PLUSOFT_PESSOA_BASE';*/
        X.*
        
  FROM NAGV_PLUSOFT_PESSOA_BASE X) Z
  
 WHERE RN = 1 AND IDPESSOA IS NOT NULL
 


