CREATE OR REPLACE VIEW CONSINCO.NAGV_PLUSOFT_VENDAS_EXT AS
SELECT /*+OPTIMIZER_FEATURES_ENABLE('11.2.0.4')*/
       DP.CPFCNPJ IDPESSOA,
       IDFILIAL, IDCUPOM, IDPRODUTO, XX.DATVENDA,
       SUM(XX.NUMQTDVENDIDA) NUMQTDVENDIDA,DATA,
       SUM(VLRPRECOVENDAUNITARIO) / SUM(XX.NUMQTDVENDIDA) VLRPRECOVENDAUNITARIO,
       SUM(VLRPRECOPDVUNITARIO) / SUM(XX.NUMQTDVENDIDA)  VLRPRECOPDVUNITARIO,
       SUM(VLRDESCONTOUNITARIO) / SUM(XX.NUMQTDVENDIDA) VLRDESCONTOUNITARIO,
       ROUND( SUM(VIMPOSTOS) / SUM(VLROPERACAO) * 100,2) VLRMARGEMPDV,
       NVL(DP.PEDIDOID, TXTCANALVENDAS) TXTCANALVENDAS, TXTTIPOVENDA, IDFORMAPAGTO , TXTFORMAPAGTO
  FROM (

SELECT /*CASE WHEN FISICAJURIDICA = 'F' THEN LPAD(NROCGCCPF,9,0)||LPAD(DIGCGCCPF,2,0)
         ELSE LPAD(NROCGCCPF,12,0)||LPAD(DIGCGCCPF,2,0) END*/
       NULL IDPESSOA,
       X.NROEMPRESA IDFILIAL,
       X.SEQNF IDCUPOM,
       X.SEQPRODUTO IDPRODUTO,
       TO_DATE(TO_CHAR(DTAOPERACAO, 'DD/MM/RRRR') || ' ' || HORAOPERACAO || ':' || MINUTOOPERACAO, 'DD/MM/RRRR HH24:MI') DATVENDA,
       QTDOPERACAO  NUMQTDVENDIDA,
       X.Vvlroperacaobruto + X.Vlracrescimo VLRPRECOVENDAUNITARIO,
       X.Vvlroperacaobruto  + X.Vlracrescimo VLRPRECOPDVUNITARIO,
       x.vlrdesconto VLRDESCONTOUNITARIO,
       X.VLROPERACAO - X.VVLRCTOLIQUIDO - X.VVLRIMPOSTOSAIDA - NVL( X.VLRDESPOPERACIONALITEM, 0 ) - X.VLRCOMISSAO- X.VLRVERBACOMPRA - X.VLRCALCIMPOSTOVDA VIMPOSTOS,
       X.VLROPERACAO VLROPERACAO,
       --DECODE(X.NROSEGMENTO,5,'E-COMMERCE',8,'E-COMMERCE','LOJA') TXTCANALVENDAS,
       CASE WHEN X.DTAOPERACAO >= DATE '2024-12-01' AND X.NROSEGMENTO IN (5,8) THEN 'GROCERY_WHITELABEL'
            WHEN X.DTAOPERACAO <  DATE '2024-12-01' AND X.NROSEGMENTO IN (5,8) THEN 'SM'
            WHEN X.NROSEGMENTO = 9 THEN 'TELEVENDAS'
            ELSE 'LOJA' END TXTCANALVENDAS,
       'VENDA' TXTTIPOVENDA,
       X.NROFORMAPAGTO IDFORMAPAGTO,
       F.DESCFORMAPAGTO TXTFORMAPAGTO,
       X.DTAOPERACAO DATA

  FROM FATO_VENDA X LEFT JOIN DIM_FORMAPAGTO F ON F.NROFORMAPAGTO = X.NROFORMAPAGTO

 WHERE 1=1
   AND X.CODGERALOPER IN (37,48,123,610,615,613,810,916,910,911,76 )
   ) XX LEFT JOIN NAGT_TMP_PLUSOFT DP ON DP.SEQNF = XX.IDCUPOM AND DP.NROEMPRESA = IDFILIAL

GROUP BY DP.CPFCNPJ, IDFILIAL, IDCUPOM, IDPRODUTO, XX.DATVENDA,
         NVL(DP.PEDIDOID, TXTCANALVENDAS), TXTTIPOVENDA,
         IDFORMAPAGTO, TXTFORMAPAGTO, DATA
;
