CREATE OR REPLACE VIEW CONSINCO.NAGV_IEAP_PROD_BASE AS
SELECT P.DESCCOMPLETA NAME,
       'https://assetsmn.s3.us-east-1.amazonaws.com/assets/ofertas/'||P.SEQPRODUTO||'.jpg' PHOTOSURL,
       P.SEQPRODUTO SKU,
       CASE WHEN F.PESAVEL = 'S' THEN 'KG' ELSE 'UN' END UNIT,
       CASE WHEN F.PESAVEL = 'S' THEN E.PESOBRUTO ELSE 1 END CLICKMULTIPLIER,
       CASE WHEN F.PESAVEL = 'S' THEN 'KG' ELSE 'UN' END SUBUNIT,
       LISTAGG(C.CODACESSO, ',') WITHIN GROUP (ORDER BY P.SEQPRODUTO) EAN,
       NULL BOOST,
       P.NOMEPRODUTOECOMM DESCRIPTION,
       M.MARCA BRAND,
       NULL SEARCHKEYWORDS,
       NULL SUBQTY,
       NULL NUTRITIONALDETAILS,
       LISTAGG(BS.SEQPRODUTO, ',') WITHIN GROUP (ORDER BY BS.SEQPRODUTO) RELATEDPRODUCTS,
       NULL INGREDIENTS,
       NULL SPECIFICATIONS,
       NULL NUTRITIONALDETAILSINFORMATION,
       NULL SUGGESTEDREPLACEMENTCLIENT,
       DECODE(P.INDINTEGRAECOMMERCE, 'S','TRUE','FALSE') ISACTIVE,
       T.FIBRA_ALIMENTAR, T.SODIO, T.GORDURAS_TOTAIS, T.PROTEINAS, T.CARBOIDRATOS,
       T.GORDURAS_SATURADAS,T.VLR_ENERGETICO, T.GORDURAS_TRANS, T.ACURARES_TTOTAIS, T.ACUCARES_ADICIONADOS

  FROM MAP_PRODUTO P INNER JOIN MAP_FAMEMBALAGEM    E  ON E.SEQFAMILIA = P.SEQFAMILIA AND E.QTDEMBALAGEM = 1
                     INNER JOIN MAP_FAMILIA F          ON F.SEQFAMILIA = P.SEQFAMILIA
                      LEFT JOIN MAP_PRODCODIGO C       ON C.SEQPRODUTO = P.SEQPRODUTO AND C.QTDEMBALAGEM = E.QTDEMBALAGEM AND C.TIPCODIGO = 'E'
                      LEFT JOIN MAP_MARCA M            ON M.SEQMARCA = F.SEQMARCA
                      LEFT JOIN MAP_INFNUTRICFAM N     ON N.SEQFAMILIA = P.SEQFAMILIA
                      LEFT JOIN MAP_PRODUTO BS         ON BS.SEQPRODUTOBASE = P.SEQPRODUTO AND BS.SEQPRODUTOBASE IS NOT NULL
                      LEFT JOIN NAGV_INFNUTRIC_PIVOT T ON T.SEQINFNUTRIC = N.SEQINFNUTRIC

 WHERE 1=1 -- P.INDINTEGRAECOMMERCE = 'S'

GROUP BY P.SEQPRODUTO, P.NOMEPRODUTOECOMM, P.DESCCOMPLETA, F.PESAVEL, E.PESOBRUTO, M.MARCA, N.SEQINFNUTRIC,
         DECODE(P.INDINTEGRAECOMMERCE, 'S','TRUE','FALSE'),
         T.FIBRA_ALIMENTAR,
         T.SODIO,
         T.GORDURAS_TOTAIS,
         T.PROTEINAS,
         T.CARBOIDRATOS,
         T.GORDURAS_SATURADAS,
         T.VLR_ENERGETICO,
         T.GORDURAS_TRANS,
         T.ACURARES_TTOTAIS,
         T.ACUCARES_ADICIONADOS
;
