CREATE OR REPLACE VIEW CONSINCO.NAGV_PLUSOFT_VENDAS AS

SELECT XX.IDPESSOA,IDFILIAL, IDCUPOM, IDPRODUTO, XX.DATVENDA, 
       SUM(XX.NUMQTDVENDIDA) NUMQTDVENDIDA, 
       SUM(VLRPRECOVENDAUNITARIO) VLRPRECOVENDAUNITARIO, 
       SUM(VLRPRECOPDVUNITARIO) VLRPRECOPDVUNITARIO,
       SUM(VLRDESCONTOUNITARIO) VLRDESCONTOUNITARIO, 
       VLRMARGEMPDV, TXTCANALVENDAS, TXTTIPOVENDA, IDFORMAPAGTO, TXTFORMAPAGTO

  FROM (

SELECT CASE WHEN FISICAJURIDICA = 'F' THEN LPAD(NROCGCCPF,9,0)||LPAD(DIGCGCCPF,2,0) 
         ELSE LPAD(NROCGCCPF,12,0)||LPAD(DIGCGCCPF,2,0) END IDPESSOA,
       X.NROEMPRESA IDFILIAL,
       X.SEQNF IDCUPOM,
       X.SEQPRODUTO IDPRODUTO,
       TO_DATE(TO_CHAR(DTAOPERACAO, 'DD/MM/RRRR') || ' ' ||
                        HORAOPERACAO || ':' || MINUTOOPERACAO,
                        'DD/MM/RRRR HH24:MI') DATVENDA, 
       QTDOPERACAO * DECODE( X.TIPCGO, 'E', -1, 1 ) NUMQTDVENDIDA,
       ROUND((NVL(NULLIF(VLRPROMOC,0), VLROPERACAO) / NVL(NULLIF(QTDOPERACAO,0), PESOBRUTO)) - NAGF_BUSCAVLRDEV(X.SEQNF, X.SEQPRODUTO),2) VLRPRECOVENDAUNITARIO,
       ROUND((NVL(NULLIF(VLRPROMOC,0), VLROPERACAO) / NVL(NULLIF(QTDOPERACAO,0), PESOBRUTO)) - NAGF_BUSCAVLRDEV(X.SEQNF, X.SEQPRODUTO),2) VLRPRECOPDVUNITARIO,
       ROUND(VLROPERACAO - NVL(NULLIF(VLRPROMOC,0), VLROPERACAO)) VLRDESCONTOUNITARIO,
       ROUND((( X.VLROPERACAO - X.VVLRCTOLIQUIDO - X.VVLRIMPOSTOSAIDA - NVL( X.VLRDESPOPERACIONALITEM, 0 ) - X.VLRCOMISSAO - X.VLRVERBACOMPRA - X.VLRCALCIMPOSTOVDA ) / (X.VLROPERACAO)*100),2) VLRMARGEMPDV,
       DECODE(X.NROSEGMENTO,5,'E-COMMERCE','LOJA') TXTCANALVENDAS,
       'VENDA' TXTTIPOVENDA,
       X.NROFORMAPAGTO IDFORMAPAGTO,
       FORMAPAGTO TXTFORMAPAGTO

  FROM FATO_VENDA@CONSINCODW X  INNER JOIN GE_PESSOA G ON G.SEQPESSOA = X.SEQCLIENTE
                                INNER JOIN MON_FORMAPAGTO F ON F.NROFORMAPAGTO = X.NROFORMAPAGTO
                                
 WHERE 1=1
   AND X.CODGERALOPER IN (37,48,123,610,615,613,810,916,910,911)
   AND NOT EXISTS (SELECT 1 FROM MFL_DOCTOFISCAL DF WHERE DF.STATUSDF = 'C' AND DF.SEQNF = X.SEQNF)

  ) XX
 
GROUP BY XX.IDPESSOA,IDFILIAL, IDCUPOM, IDPRODUTO, XX.DATVENDA, 
         VLRMARGEMPDV, TXTCANALVENDAS, TXTTIPOVENDA,
         IDFORMAPAGTO, TXTFORMAPAGTO

ORDER BY 9 ASC

-- NO DW

CREATE OR REPLACE VIEW NAGV_PLUSOFT_VENDAS AS
SELECT XX.IDPESSOA,IDFILIAL, IDCUPOM, IDPRODUTO, XX.DATVENDA,
       SUM(XX.NUMQTDVENDIDA) NUMQTDVENDIDA,DATA,
       SUM(VLRPRECOVENDAUNITARIO) / SUM(XX.NUMQTDVENDIDA) VLRPRECOVENDAUNITARIO,
       SUM(VLRPRECOPDVUNITARIO) / SUM(XX.NUMQTDVENDIDA)  VLRPRECOPDVUNITARIO,
       SUM(VLRDESCONTOUNITARIO) / SUM(XX.NUMQTDVENDIDA) VLRDESCONTOUNITARIO,
       ROUND( SUM(VIMPOSTOS) / SUM(VLROPERACAO) * 100,2) VLRMARGEMPDV,
       TXTCANALVENDAS, TXTTIPOVENDA, IDFORMAPAGTO , TXTFORMAPAGTO
  FROM (

SELECT CASE WHEN FISICAJURIDICA = 'FISICA' THEN LPAD(G.NROCPFCNPJ,11,0) WHEN G.FISICAJURIDICA = 'JURIDICA'  THEN LPAD(G.NROCPFCNPJ,14,0) ELSE LPAD(G.NROCPFCNPJ,11,0) END IDPESSOA,
       X.NROEMPRESA IDFILIAL,
       X.SEQNF IDCUPOM,
       X.SEQPRODUTO IDPRODUTO,
       TO_DATE(TO_CHAR(DTAOPERACAO, 'DD/MM/RRRR') || ' ' || HORAOPERACAO || ':' || MINUTOOPERACAO, 'DD/MM/RRRR HH24:MI') DATVENDA,
       QTDOPERACAO  NUMQTDVENDIDA,
       --(X.Vvlroperacaobruto) VLRPRECOVENDAUNITARIO,
       --(X.Vvlroperacaobruto) VLRPRECOPDVUNITARIO,
       X.Vvlroperacaobruto + X.Vlracrescimo VLRPRECOVENDAUNITARIO,
       X.Vvlroperacaobruto  + X.Vlracrescimo VLRPRECOPDVUNITARIO,
       x.vlrdesconto VLRDESCONTOUNITARIO,
/*     ROUND((( X.VLROPERACAO - X.VVLRCTOLIQUIDO - X.VVLRIMPOSTOSAIDA - NVL( X.VLRDESPOPERACIONALITEM, 0 ) - X.VLRCOMISSAO- X.VLRVERBACOMPRA - X.VLRCALCIMPOSTOVDA ) / (X.VLROPERACAO)*100),2) VLRMARGEMPDV_OLD,   */     
       X.VLROPERACAO - X.VVLRCTOLIQUIDO - X.VVLRIMPOSTOSAIDA - NVL( X.VLRDESPOPERACIONALITEM, 0 ) - X.VLRCOMISSAO- X.VLRVERBACOMPRA - X.VLRCALCIMPOSTOVDA VIMPOSTOS,
       X.VLROPERACAO VLROPERACAO,
       DECODE(X.NROSEGMENTO,5,'E-COMMERCE',8,'E-COMMERCE','LOJA') TXTCANALVENDAS,
       'VENDA' TXTTIPOVENDA,
       X.NROFORMAPAGTO IDFORMAPAGTO,
       F.DESCFORMAPAGTO TXTFORMAPAGTO,
       X.DTAOPERACAO DATA

  FROM FATO_VENDA X  INNER JOIN DIM_CLIENTE G ON G.SEQCLIENTE = X.SEQCLIENTE
                     INNER JOIN DIM_FORMAPAGTO F ON F.NROFORMAPAGTO = X.NROFORMAPAGTO

 WHERE 1=1
   AND X.CODGERALOPER IN (37,48,123,610,615,613,810,916,910,911)) XX

GROUP BY XX.IDPESSOA,IDFILIAL, IDCUPOM, IDPRODUTO, XX.DATVENDA,
         TXTCANALVENDAS, TXTTIPOVENDA,
         IDFORMAPAGTO, TXTFORMAPAGTO, DATA
;
