ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

CREATE OR REPLACE VIEW CONSINCO.NAGV_PLUSOFT_PESSOA AS

SELECT CASE WHEN FISICAJURIDICA = 'F' THEN LPAD(NROCGCCPF,9,0)||LPAD(DIGCGCCPF,2,0) 
         ELSE LPAD(NROCGCCPF,12,0)||LPAD(DIGCGCCPF,2,0) END IDPESSOA,
       X.NOMERAZAO TXTNOMECOMPLETO,
       X.ESTADOCIVIL TXTESTADOCIVIL,
       X.SEXO TXTSEXO,
       X.DTANASCFUND DATNASCIMENTO,
       C.DTAULTCOMPRA DATULTCOMPRA,
       X.DTAALTERACAO DATATUALIZACAOCADASTRO,
       X.DTAINCLUSAO DATCADASTRO,
       X.FONENRO1 NUMCEL1,
       X.FONENRO2 NUMCEL2,
       X.FAXNRO NUMTELFIXO,
       NULL NUMTELCOMERCIAL,
       X.EMAIL TXTEMAIL,
       X.LOGRADOURO || CASE WHEN X.NROLOGRADOURO = '0' THEN NULL ELSE ' - '||X.NROLOGRADOURO END TXTENDERECO,
       X.BAIRRO TXTBAIRRO,
       X.CIDADE TXTCIDADE,
       X.UF TXTESTADO 
       
  FROM CONSINCO.GE_PESSOA X INNER JOIN MRL_CLIENTE C ON C.SEQPESSOA = X.SEQPESSOA
 WHERE 1 = 1
   AND X.SEQPESSOA > 999
   AND X.STATUS = 'A'

-- NO DW

CREATE OR REPLACE VIEW NAGV_PLUSOFT_PESSOA AS
SELECT CASE WHEN FISICAJURIDICA = 'F' THEN LPAD(NROCGCCPF,9,0)||LPAD(DIGCGCCPF,2,0)
         ELSE LPAD(NROCGCCPF,12,0)||LPAD(DIGCGCCPF,2,0) END IDPESSOA,
       X.NOMERAZAO TXTNOMECOMPLETO,
       X.ESTADOCIVIL TXTESTADOCIVIL,
       X.SEXO TXTSEXO,
       X.DTANASCFUND DATNASCIMENTO,
       C.DTAULTCOMPRA DATULTCOMPRA,
       X.DTAALTERACAO DATATUALIZACAOCADASTRO,
       X.DTAINCLUSAO DATCADASTRO,
       X.FONENRO1 NUMCEL1,
       X.FONENRO2 NUMCEL2,
       X.FAXNRO NUMTELFIXO,
       NULL NUMTELCOMERCIAL,
       X.EMAIL TXTEMAIL,
       X.LOGRADOURO || CASE WHEN X.NROLOGRADOURO = '0' THEN NULL ELSE ' - '||X.NROLOGRADOURO END TXTENDERECO,
       X.BAIRRO TXTBAIRRO,
       X.CIDADE TXTCIDADE,
       X.UF ESTADO

  FROM GE_PESSOA@LINK_C5 X INNER JOIN MRL_CLIENTE@LINK_C5 C ON C.SEQPESSOA = X.SEQPESSOA
 WHERE 1 = 1
   AND X.SEQPESSOA > 999
   AND X.STATUS = 'A';
